[package]
name = "agntcy-shadi-sandbox-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"

[dependencies.agntcy-shadi-sandbox]
path = ".."

[[bin]]
name = "control-message"
path = "fuzz_targets/control-message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "session-name"
path = "fuzz_targets/session-name.rs"
test = false
doc = false
bench = false

[workspace]
