site_name: SHADI
site_description: Secure Host Agentic AI Dynamic Instantiation
site_url: https://agntcy.github.io/shadi
repo_url: https://github.com/agntcy/shadi
repo_name: shadi

extra:
  copyright: >
    Copyright SHADI Contributors.

extra_css:
  - stylesheets/custom.css

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  logo_light: assets/img/logo-light.svg
  logo_dark: assets/img/logo-dark.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

nav:
  - Introduction:
      - Overview: index.md
      - Architecture: architecture.md
      - Security Notes: security.md
      - Design Overview: design.md
  - Guides:
      - Install the CLI: install.md
      - Getting Started: getting_started.md
      - Operations: operations.md
      - Telemetry: telemetry.md
      - Sandbox and Policies: sandbox.md
  - Integrations:
      - API Guide: api_integration.md
      - SLIM and A2A: slim_a2a.md
      - Mobile: mobile_integration.md
  - Reference:
      - CLI Reference: cli.md

exclude_docs: |
  README.md

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - toc:
      permalink: true
  - codehilite

plugins:
  - search
