[workspace]
release_always = true
publish = true
publish_no_verify = true
publish_timeout = "30m"

[[package]]
name = "shadi_demo_bot"
publish = false
release = false

[[package]]
name = "agentbridge_demo"
publish = false
release = false