[package]
name = "agntcy-shadi-identity-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.agntcy-shadi-identity]
path = ".."

[[bin]]
name = "did-proof"
path = "fuzz_targets/did-proof.rs"
test = false
doc = false
bench = false

[workspace]
