[package]
name = "agntcy-shadi-agent-transport-slim"
version = "0.2.0"
edition = "2021"
description = "SLIM transport integration and stdio bridge support for SHADI."
license.workspace = true
repository.workspace = true

[lib]
name = "agent_transport_slim"

[features]
default = []
slim = []

[dependencies]
agent_secrets = { package = "agntcy-shadi-agent-secrets", version = "0.2.0", path = "../agent_secrets" }
shadi_identity = { package = "agntcy-shadi-identity", version = "0.1.0", path = "../shadi_identity" }
slim_bindings = { package = "agntcy-slim-bindings", version = "2.0.0-alpha.8" }
